disabled_rules:
- line_length
- trailing_whitespace

included:
excluded:
- Pods
- PapagoTalk/SceneDelegate.swift
- PapagoTalk/AppDelegate.swift
- PapagoTalk/GraphQL/API.swift
function_body_length: 200
