disabled_rules:
- line_length
- trailing_whitespace
- unused_capture_list
- multiple_closures_with_trailing_closure

included:
excluded:
- Pods
- PapagoTalk/SceneDelegate.swift
- PapagoTalk/AppDelegate.swift
- PapagoTalk/GraphQL/API.swift
identifier_name:
  min_length: 1
function_body_length: 200
